import React from "react";
import { Grid, Typography, Paper } from "@mui/material";

function PrivacyPolicy() {
  return (
    <Grid style={{ backgroundColor: "#83bec9", padding: "50px" }}>
      <Paper elevation={1} style={{ borderRadius: "50px", padding: "20px" }}>
        <Typography
          variant="h4"
          style={{
            textAlign: "center",
            color: "#05445e",
            padding: "3%",
            fontWeight: "bold",
            fontSize: "30px",
            fontFamily: "poppins, sans-sarif",
          }}
        >
          Privacy Policy
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "30px",
            fontSize: "13px",
          }}
        >
          Even HapiDoc Private Limited (hereinafter referred to as "Even" / “we”
          / “us”) is committed towards protecting your personally identifiable
          information, including sensitive personal data (“Personal
          Information”) that’s collected by Even from you whilst you use our
          website and/or mobile application (collectively referred to as the
          “Website”).
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "20px",
            fontSize: "13px",
          }}
        >
          Even collects, processes and treats the Personal Information of its
          users in compliance with the provisions of the Information Technology
          Act, 2000 and the Information Technology (Reasonable Security and
          Procedures and Sensitive Personal Data or Information) Rules, 2011
          (“Data Protection Laws”), to the extent applicable for such Personal
          Information.
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "20px",
            fontSize: "13px",
          }}
        >
          This Privacy Policy represents the complete statement of Even’s
          practices with respect to the collection of Personal Information
          through the Website and how it’s used.
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "20px",
            fontSize: "13px",
          }}
        >
          Please read this Privacy Policy carefully before proceeding to use our
          Website. By using the Website, you agree to be legally bound by the
          terms and conditions of this Privacy Policy, which shall take effect
          immediately on your first use of the Website. If you don’t agree, then
          please do not continue to access or use the Website and do not
          complete the registration process on the Website.
        </Typography>
        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            fontWeight: 600,
            marginTop: "30px",
            fontSize: "16px",
          }}
        >
          1. SCOPE OF THE PRIVACY POLICY
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          The purpose of this Privacy Policy is to outline and help you
          understand the various procedure followed by Even when collecting,
          storing, utilising, disclosing or otherwise dealing with any Personal
          Information.
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "20px",
            fontSize: "13px",
          }}
        >
          Further, the Website may contain hyperlinks to third-party websites or
          social media websites operated by parties other than Even which are
          developed by people that Even has no control over, this includes
          social media plug-ins. This Privacy Policy does not apply to the
          practices of such websites. Such other websites may place their own
          cookies on your computer/electronic device, collect data or solicit
          Personal Information. Even is accordingly not and shall not be deemed
          to be responsible in any way for the privacy practices of such
          websites.
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "20px",
            fontSize: "13px",
          }}
        >
          Any summary of this Privacy Policy generated by third party software
          or otherwise shall have no legal effect, shall not be binding on Even,
          shall not be relied upon in substitute for this Privacy Policy, and
          neither supersede nor modify this Privacy Policy.
        </Typography>
        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            fontWeight: 600,
            marginTop: "30px",
            fontSize: "16px",
          }}
        >
          2. PAYMENT RELATED INFORMATION
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          All payment transactions happen using Secure Server Software through
          third party payment gateways. Even does not have end to end control
          over such transactions, and shall in no way be responsible or liable
          for any loss or damage due to any disclosure of your payment related
          information.
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          Even hereby disclaims all its liability and shall in no way be liable
          or responsible for any loss or damage caused to you on account of
          intentional or unintentional disclosure of any Personal Information
          concerning your account and/or any information with respect to any
          online payment transaction handled by third party payment gateways
          using the credit card/debit card/cash card/net-banking/mobile
          wallet/UPI, etc. and/or the payment verification process.
        </Typography>

        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            fontWeight: 600,
            marginTop: "30px",
            fontSize: "16px",
          }}
        >
          3. USE AND DISCLOSURE OF COLLECTED INFORMATION
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          When any Personal Information is provided by you to Even in the course
          of your access to the Website, that information provided shall be used
          by Even and its service providers and partners, including hospitals
          and other HapiDoc providers, for the purposes of providing Even’s
          services (online and offline), fulfil our service obligations,
          conducting background screening, facilitating any customer requests,
          and carrying out activities connected with the running of our business
          such as personnel training, quality control, and service monitoring.
        </Typography>

        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            fontWeight: 600,
            marginTop: "30px",
            fontSize: "16px",
          }}
        >
          4. USE OF PERSONAL INFORMATION FOR MARKETING AND CONTACT
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          In addition, Even also reserves the right to use your Personal
          Information to contact you and deliver information targeted to your
          interests, such as banner advertisements, notices, service offerings,
          communications, newsletters, SMS messages, etc., relevant to your
          interests and use of the Website. By accepting the Terms of Use and
          this Privacy Policy, you expressly agree to receive such information
          and communications. In case you do not wish to receive such
          information and communications, then we request you to kindly
          unsubscribe/opt out of the receipt of such information and
          communications.
        </Typography>

        {/* Section 6: Disclosure of Personal Information */}
        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            fontWeight: 600,
            marginTop: "30px",
            fontSize: "16px",
          }}
        >
          5. DISCLOSURE OF PERSONAL INFORMATION
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          Even treats your Personal Information and your use of Even’s services
          as private and confidential and does not disclose your Personal
          Information to third parties, except as may be necessary to provide
          Even’s services, and under the following specific circumstances:
        </Typography>
        <Typography
          variant="h9"
          style={{
            color: "#05445e",
            fontFamily: "poppins, sans-sarif",
            fontSize: "13px",
          }}
        >
          <ul>
            <li>
              To insurance companies, hospitals, physicians or other HapiDoc
              providers that provide services directly to you on our behalf. To
              enable them to do this and related activities such as billing, we
              may need to share your Personal Information, including access to
              your medical reports for diagnosis, treatment etc;
            </li>
            <li>
              To enforce the Terms of Use which are binding on all the users of
              the Website;
            </li>
            <li>
              To respond to summons, court orders, or legal process, or to
              establish or exercise our legal rights or defend against legal
              claims;
            </li>
            <li>To any governmental body as and when required under law.</li>
          </ul>
        </Typography>

        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "30px",
            fontSize: "16px",
            fontWeight: 600,
          }}
        >
          6. SHARING OF GENERAL STATISTICAL INFORMATION
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          In addition to the above, Even may record and share general
          statistical information of its users and the services used with
          selected clients, service providers and partners of Even, without
          disclosing individual names or personally identifying information of
          the users of the Website. In the event that another company acquires
          all or substantially all of the assets of Even’s business through a
          consolidation, merger, asset purchase or other transaction, Even
          reserves the right to transfer all data (including any Personal
          Information) that is in its possession or under its control to such
          acquiring party and subsequently the privacy policy of the acquiring
          party shall govern all such data and any Personal Information that has
          been transferred.
        </Typography>

        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "30px",
            fontSize: "16px",
            fontWeight: 600,
          }}
        >
          7. ACCESS TO YOUR PERSONAL INFORMATION
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          For information collected through the Website, users can send an
          e-mail or letter to the Grievance Officer to:
        </Typography>
        <Typography
          variant="h9"
          style={{
            color: "#05445e",
            fontFamily: "poppins, sans-sarif",
            fontSize: "13px",
          }}
        >
          <ul>
            <li>
              Access Personal Information that the Website has collected from
              the user through your access to and use of the services provided
              through the Website;
            </li>
            <li>Correct any factual errors in such Personal Information; or</li>
            <li>
              Request to have your Personal Information deleted from Even’s
              servers.
            </li>
          </ul>
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          To protect the privacy and security of our users, Even will take
          reasonable steps to verify your identity before granting you access to
          your Personal Information that is collected and maintained by Even.
        </Typography>

        {/* Section 7: Information We Collect from Third Parties */}
        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "30px",
            fontSize: "16px",
            fontWeight: 600,
          }}
        >
          8. INFORMATION WE COLLECT FROM THIRD PARTIES
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          We will ordinarily collect your Personal Information from you
          directly. However, we may occasionally, request your Personal
          Information from certain third parties such as your physician,
          hospital, or any other HapiDoc provider, for purposes such as
          providing and improving our services, fulfilling our contractual
          obligations to you, billing, conducting background screening, and
          carrying out any other activity related or incidental thereto. By
          completing the registration process on the Website and the use of
          Even’s services, you hereby consent to such third parties sharing such
          Personal Information with Even, and Even collecting, processing and
          storing such information for the abovementioned purposes.
        </Typography>

        {/* Section 8: Amendments to the Policy */}
        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "30px",
            fontSize: "16px",
            fontWeight: 600,
          }}
        >
          9. AMENDMENTS TO THE POLICY
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          This Policy is based on current laws and regulations applicable in
          India, and may be revised in view of any changes in law in India, as
          applicable to Even.
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          Even reserves the right to put out revisions/modifications to this
          Privacy Policy, and any of its other procedures concerning the
          treatment of information collected through the Website, without any
          prior notice. Any changes to this Privacy Policy will become effective
          upon posting of the revised Privacy Policy on the Website. Access/use
          of the Website following the posting of the Privacy Policy will be
          considered as your acceptance of the revised Privacy Policy.
        </Typography>

        {/* Section 10: Governing Law and Dispute Resolution */}
        <Typography
          variant="h6"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "30px",
            fontSize: "16px",
            fontWeight: 600,
          }}
        >
          10. GOVERNING LAW AND DISPUTE RESOLUTION
        </Typography>
        <Typography
          variant="body1"
          gutterBottom
          style={{
            fontFamily: "poppins, sans-serif",
            marginTop: "10px",
            fontSize: "13px",
          }}
        >
          This Privacy Policy shall be governed by the laws of India. Any and
          all disputes arising under or in relation to this Privacy Policy shall
          be subject to the exclusive jurisdiction of courts in Bengaluru.
        </Typography>
      </Paper>
    </Grid>
  );
}

export default PrivacyPolicy;
